version: "2"
services:
  python:
    image: python:2.7
    volumes:
      - ./:/code
    working_dir: /code
    ports:
     - "8888:8888"
    command: /bin/bash -c "pip install -r requirements.txt && exec invoke run_dev"